# Generated by Django 5.2.15 on 2026-06-19 11:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="bio",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="commission_rate",
            field=models.PositiveSmallIntegerField(
                default=0, help_text="Platform commission percentage (0–100)"
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="is_approved",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="logo_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="seller_profile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="wa_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
