# Generated by Django 5.2.15 on 2026-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sellerprofile_bio_sellerprofile_commission_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="notif_email",
            field=models.BooleanField(default=True, help_text="Receive notifications via email"),
        ),
        migrations.AddField(
            model_name="customer",
            name="notif_wa",
            field=models.BooleanField(default=True, help_text="Receive notifications via WhatsApp"),
        ),
    ]
