# Generated by Django 5.2.15 on 2026-06-20 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_customer_notif_prefs"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="custom_domain",
            field=models.CharField(blank=True, help_text="e.g. shop.example.com", max_length=253),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="fb_pixel_id",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="ga_tracking_id",
            field=models.CharField(blank=True, help_text="e.g. G-XXXXXXXXXX", max_length=30),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="kyc_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="payout_account_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="payout_account_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="payout_bank_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="plan",
            field=models.CharField(
                choices=[("free", "Free"), ("pro", "PRO")], default="free", max_length=10
            ),
        ),
    ]
