# Generated by Django 5.2.15 on 2026-07-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sellerprofile_custom_domain_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="onboarding_completed",
            field=models.BooleanField(
                default=True,
                help_text="False forces the seller through the guided store-setup wizard (apply() sets this to False for every newly-created SellerProfile).",
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="onboarding_step",
            field=models.CharField(
                choices=[
                    ("identity", "Store identity"),
                    ("product", "First product"),
                    ("publish", "Publish"),
                ],
                default="identity",
                help_text="Where a not-yet-onboarded seller resumes the setup wizard.",
                max_length=20,
            ),
        ),
    ]
