# Generated by Django 5.2.15 on 2026-08-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_sellerprofile_onboarding_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sellerprofile",
            name="qris_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="qris_image",
            field=models.ImageField(blank=True, null=True, upload_to="qris/"),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="qris_instructions",
            field=models.TextField(
                blank=True,
                help_text="Shown to the buyer on the payment screen — e.g. transfer the exact amount, then upload your receipt.",
            ),
        ),
    ]
