# Generated by Django 5.2.15 on 2026-08-29 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_sellerprofile_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="terms_accepted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the user accepted the Terms of Service and Privacy Policy.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="sellerprofile",
            name="agreement_accepted_at",
            field=models.DateTimeField(
                blank=True, help_text="When the seller accepted the Seller Agreement.", null=True
            ),
        ),
    ]
