# Generated by Django 5.2.15 on 2026-06-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                help_text="Caller-supplied key for safe checkout retry",
                max_length=200,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="topup",
            name="checkout_order",
            field=models.OneToOneField(
                blank=True,
                help_text="Top-up-and-buy: complete this Order after TopUp is credited",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="funding_topup",
                to="billing.order",
            ),
        ),
    ]
