# Generated by Django 5.2.15 on 2026-06-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_topup_checkout_order_order_idempotency_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="subscription",
            field=models.ForeignKey(
                blank=True,
                help_text="Subscription created by this Order (recurring plans only)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="billing.subscription",
            ),
        ),
    ]
