# Generated by Django 5.2.15 on 2026-06-19 11:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_sellerprofile_bio_sellerprofile_commission_rate_and_more"),
        ("billing", "0003_grant_order_order_subscription"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Coupon discount applied (IDR)"
            ),
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=50, unique=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percent (%)"), ("fixed", "Fixed (Rp)")],
                        default="percent",
                        max_length=10,
                    ),
                ),
                (
                    "value",
                    models.PositiveBigIntegerField(help_text="Percent 1–100 or fixed Rp amount"),
                ),
                (
                    "min_order",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Min order amount to apply (0 = no minimum)"
                    ),
                ),
                (
                    "max_discount",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Cap on discount IDR (0 = no cap, percent type)"
                    ),
                ),
                (
                    "usage_limit",
                    models.PositiveIntegerField(
                        default=0, help_text="Max redemptions (0 = unlimited)"
                    ),
                ),
                ("used_count", models.PositiveIntegerField(default=0)),
                ("valid_from", models.DateTimeField(blank=True, null=True)),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Restrict to specific plans (empty = all)",
                        to="catalog.plan",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupons",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="billing.coupon",
            ),
        ),
    ]
