# Generated by Django 5.2.15 on 2026-06-19 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0004_order_discount_coupon_order_coupon"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_number",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Sequential invoice number, assigned when order is marked PAID",
                null=True,
                unique=True,
            ),
        ),
    ]
