# Generated by Django 5.2.15 on 2026-06-20 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0005_add_order_invoice_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="custom_fields",
            field=models.JSONField(
                blank=True, default=dict, help_text="Buyer answers to ProductQuestion intake fields"
            ),
        ),
    ]
