# Generated by Django 5.2.15 on 2026-06-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sellerprofile_custom_domain_and_more"),
        ("billing", "0006_order_custom_fields"),
        ("catalog", "0004_coursemodule_courselesson_courseprogress"),
    ]

    operations = [
        migrations.CreateModel(
            name="AffiliateLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=30, unique=True)),
                (
                    "commission_rate",
                    models.PositiveSmallIntegerField(
                        default=10, help_text="Commission % of net order amount for the affiliate"
                    ),
                ),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "label",
                    models.CharField(
                        blank=True, help_text="Internal label for tracking", max_length=100
                    ),
                ),
                (
                    "affiliate_seller",
                    models.ForeignKey(
                        blank=True,
                        help_text="The promoter (another seller). Null = external promoter.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliate_promotions",
                        to="accounts.sellerprofile",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        help_text="Restrict to this product. Null = applies to all seller products.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="affiliate_links",
                        to="catalog.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="Product seller who owns this link programme",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affiliate_links",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AffiliateCommission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveBigIntegerField(help_text="Commission earned (IDR)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid_out", "Paid Out"),
                            ("voided", "Voided"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="affiliate_commission",
                        to="billing.order",
                    ),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="commissions",
                        to="billing.affiliatelink",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerEarning",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("gross", models.PositiveBigIntegerField(help_text="Order amount (IDR)")),
                (
                    "commission",
                    models.PositiveBigIntegerField(default=0, help_text="Platform fee (IDR)"),
                ),
                ("net", models.PositiveBigIntegerField(help_text="Seller receives (IDR)")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid_out", "Paid Out"),
                            ("voided", "Voided"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="seller_earning",
                        to="billing.order",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="earnings",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["seller", "status"], name="billing_sel_seller__020c1b_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="SellerPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("amount", models.PositiveBigIntegerField(help_text="Requested withdrawal (IDR)")),
                ("bank_name", models.CharField(max_length=100)),
                ("account_number", models.CharField(max_length=50)),
                ("account_name", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "seller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payouts",
                        to="accounts.sellerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["seller", "status"], name="billing_sel_seller__ff34db_idx")
                ],
            },
        ),
    ]
