# Generated by Django 5.2.15 on 2026-06-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0007_affiliatelink_affiliatecommission_sellerearning_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="duration_multiplier",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Number of base intervals prepaid (e.g. 6 on a monthly plan = 6 months)",
            ),
        ),
    ]
