# Generated by Django 5.2.15 on 2026-08-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0009_cart_cartcheckout_order_cart_checkout_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_channel",
            field=models.CharField(
                choices=[
                    ("wallet", "Wallet"),
                    ("gateway", "Payment Gateway"),
                    ("qris_static", "QRIS Statis"),
                ],
                default="wallet",
                help_text="How the buyer paid. 'qris_static' orders stay PENDING until the seller manually confirms receipt.",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_proof",
            field=models.ImageField(
                blank=True,
                help_text="Optional payment receipt uploaded by the buyer (QRIS Statis).",
                null=True,
                upload_to="payment_proofs/",
            ),
        ),
    ]
