# Generated by Django 5.2.15 on 2026-08-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_cart_cartcheckout_order_cart_checkout_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topup',
            name='gateway',
            field=models.CharField(choices=[('sumopod', 'Sumopod'), ('duitku', 'Duitku')], default='sumopod', max_length=20),
        ),
    ]
