# Generated by Django 5.2.15 on 2026-08-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0010_alter_topup_gateway"),
    ]

    operations = [
        migrations.AddField(
            model_name="topup",
            name="gateway_fee",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Gateway fee (IDR) paid by the customer on top of amount"
            ),
        ),
    ]
