upstream tennis_table {
    server tennis-table-web:8000;
}

server {
    listen 80;
    server_name synergycup.interport.roc.web.id;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    http2 on;
    server_name synergycup.interport.roc.web.id;

    ssl_certificate     /etc/letsencrypt/live/synergycup.interport.roc.web.id/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/synergycup.interport.roc.web.id/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    client_max_body_size 10M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        proxy_pass http://tennis_table;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}
