# Generated by Django 5.2.15 on 2026-06-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("billing", "0001_initial"),
        ("catalog", "0001_initial"),
        ("provisioning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(
                        editable=False,
                        help_text="XXXX-XXXX-XXXX Crockford Base32 (ADR-007)",
                        max_length=14,
                        unique=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("seat_limit", models.PositiveIntegerField(default=1)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="accounts.customer",
                    ),
                ),
                (
                    "grant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="license",
                        to="provisioning.grant",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="licenses",
                        to="catalog.plan",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="licenses",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Installation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "fingerprint",
                    models.CharField(help_text="Unique device/machine identity", max_length=200),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="User-provided device label", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("deactivated", "Deactivated")],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("last_seen", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "license",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="installations",
                        to="licensing.license",
                    ),
                ),
            ],
            options={
                "ordering": ["-activated_at"],
            },
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(fields=["key"], name="licensing_l_key_46fcea_idx"),
        ),
        migrations.AddIndex(
            model_name="license",
            index=models.Index(
                fields=["customer", "status"], name="licensing_l_custome_5bb12c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="installation",
            index=models.Index(fields=["license", "status"], name="licensing_i_license_db0e04_idx"),
        ),
        migrations.AddIndex(
            model_name="installation",
            index=models.Index(fields=["fingerprint"], name="licensing_i_fingerp_736f93_idx"),
        ),
        migrations.AddConstraint(
            model_name="installation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("license", "fingerprint"),
                name="unique_active_fingerprint_per_license",
            ),
        ),
    ]
