# Generated by Django 5.2.15 on 2026-06-18 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wallet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("balance", models.PositiveBigIntegerField(default=0)),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wallet",
                        to="accounts.customer",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="LedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("topup", "Top-up"),
                            ("purchase", "Purchase"),
                            ("renewal", "Renewal"),
                            ("refund", "Refund"),
                            ("adjustment", "Adjustment"),
                            ("bonus", "Bonus"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.BigIntegerField()),
                ("balance_after", models.PositiveBigIntegerField()),
                ("ref", models.CharField(max_length=200, unique=True)),
                ("note", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="entries",
                        to="wallet.wallet",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["wallet", "created_at"], name="wallet_ledg_wallet__9a50b7_idx"
                    ),
                    models.Index(fields=["ref"], name="wallet_ledg_ref_06d75b_idx"),
                ],
            },
        ),
    ]
