# Generated by Django 5.2.15 on 2026-06-19 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="cover_image_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Cover image URL shown on the storefront (optional)",
            ),
        ),
    ]
