# Generated by Django 5.2.15 on 2026-06-20 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0006_order_custom_fields"),
        ("catalog", "0002_add_cover_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="min_price",
            field=models.PositiveBigIntegerField(
                default=0, help_text="Minimum price for PWYW (0 = no minimum)"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="pwyw",
            field=models.BooleanField(
                default=False, help_text="Pay-what-you-want: buyer sets the price"
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="sale_price",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Strike-through original price shown on storefront", null=True
            ),
        ),
        migrations.AddField(
            model_name="plan",
            name="stock_quantity",
            field=models.PositiveIntegerField(
                blank=True, help_text="Stock limit (null = unlimited)", null=True
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="purchase_button_label",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Override Buy button text (default: 'Buy Now')",
                max_length=60,
            ),
        ),
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("label", models.CharField(max_length=200)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Short text"),
                            ("email", "Email"),
                            ("phone", "Phone number"),
                        ],
                        default="text",
                        max_length=20,
                    ),
                ),
                ("required", models.BooleanField(default=False)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        help_text="1–5 stars",
                    ),
                ),
                ("text", models.TextField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="billing.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
