# Generated by Django 5.2.15 on 2026-06-20 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_add_customer_notif_prefs"),
        ("catalog", "0003_plan_min_price_plan_pwyw_plan_sale_price_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["product", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CourseLesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                (
                    "lesson_type",
                    models.CharField(
                        choices=[("video", "Video"), ("text", "Text"), ("file", "File download")],
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, help_text="Text content or video embed URL"),
                ),
                (
                    "file_url",
                    models.URLField(blank=True, help_text="Direct file URL (for file lessons)"),
                ),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                (
                    "is_preview",
                    models.BooleanField(
                        default=False, help_text="Accessible without purchase (free preview)"
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="catalog.coursemodule",
                    ),
                ),
            ],
            options={
                "ordering": ["module", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_progress",
                        to="accounts.customer",
                    ),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress",
                        to="catalog.courselesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-completed_at"],
                "unique_together": {("customer", "lesson")},
            },
        ),
    ]
