# Generated by Django 5.2.15 on 2026-06-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_coursemodule_courselesson_courseprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="duration_discounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Discount % per multiplier. E.g. {"3":5,"6":10,"12":15} = 3× gets 5% off. Only for recurring plans.',
            ),
        ),
    ]
