# Generated by Django 5.2.15 on 2026-06-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_plan_duration_discounts_order_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="plan",
            name="direct_pay",
            field=models.BooleanField(
                default=True,
                help_text="Buyer pays via payment gateway directly, bypassing wallet balance. Only active when DIRECT_PAY_ENABLED master setting is true.",
            ),
        ),
    ]
