# Generated by Django 5.2.15 on 2026-08-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_plan_direct_pay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="duration_discounts",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text='Duration Plan tiers: prepaid-interval multiplier → discount %. E.g. {"3":5,"6":10,"12":0} = 3× gets 5% off, 12× is offered with no discount. Discount is optional (0 = plain prepay option). Only for recurring plans.',
            ),
        ),
    ]
