# Generated by Django 5.2.15 on 2026-08-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_plan_duration_discounts"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="cover_image_url",
        ),
        migrations.AddField(
            model_name="product",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Cover image shown on the storefront (optional)",
                null=True,
                upload_to="product/cover/",
            ),
        ),
    ]
