# Generated by Django 5.2.15 on 2026-06-18 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("billing", "0001_initial"),
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("license_key", "License Key"),
                            ("credentials", "Credentials"),
                            ("account", "Account"),
                            ("download", "Download"),
                            ("access_link", "Access Link"),
                            ("api_key", "API Key"),
                            ("manual", "Manual"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "config",
                    models.JSONField(
                        blank=True, default=dict, help_text="Provisioner-specific config"
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deliverables",
                        to="catalog.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "key",
                    models.CharField(help_text='e.g. "PRO_EXPORT", "MAX_PROJECTS"', max_length=100),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "value",
                    models.CharField(
                        blank=True, help_text='e.g. "10" for MAX_PROJECTS', max_length=200
                    ),
                ),
                (
                    "plans",
                    models.ManyToManyField(
                        blank=True, related_name="entitlements", to="catalog.plan"
                    ),
                ),
            ],
            options={
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("license_key", "License Key"),
                            ("credentials", "Credentials"),
                            ("account", "Account"),
                            ("download", "Download"),
                            ("access_link", "Access Link"),
                            ("api_key", "API Key"),
                            ("manual", "Manual"),
                        ],
                        help_text="Denormalized from deliverable.type for fast lookup",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("suspended", "Suspended"),
                            ("revoked", "Revoked"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='Artifact reference, e.g. {"license_id": 42}',
                    ),
                ),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="accounts.customer",
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="grants",
                        to="provisioning.deliverable",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="grants",
                        to="billing.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Secret",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("ciphertext", models.TextField(help_text="Encrypted credential — Fernet base64")),
                ("is_revealed", models.BooleanField(default=False)),
                ("rotated_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="secret",
                        to="provisioning.grant",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(
                fields=["customer", "status"], name="provisionin_custome_0dd1e5_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="grant",
            index=models.Index(fields=["type", "status"], name="provisionin_type_537325_idx"),
        ),
    ]
