# Generated by Django 5.2.15 on 2026-06-18 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0003_grant_order_order_subscription"),
        ("provisioning", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="grant",
            name="order",
            field=models.ForeignKey(
                blank=True,
                help_text="The Order that created this Grant — null for manually issued grants",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="grants",
                to="billing.order",
            ),
        ),
    ]
