# Generated by Django 5.2.15 on 2026-06-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0002_grant_order_order_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="instructions",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Post-purchase instructions shown to the buyer (plain text or markdown)",
            ),
        ),
    ]
