# Generated by Django 5.2.15 on 2026-06-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("provisioning", "0003_add_deliverable_instructions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="type",
            field=models.CharField(
                choices=[
                    ("license_key", "License Key"),
                    ("credentials", "Credentials"),
                    ("account", "Account"),
                    ("download", "Download"),
                    ("access_link", "Access Link"),
                    ("api_key", "API Key"),
                    ("manual", "Manual"),
                    ("course", "Course Access"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="grant",
            name="type",
            field=models.CharField(
                choices=[
                    ("license_key", "License Key"),
                    ("credentials", "Credentials"),
                    ("account", "Account"),
                    ("download", "Download"),
                    ("access_link", "Access Link"),
                    ("api_key", "API Key"),
                    ("manual", "Manual"),
                    ("course", "Course Access"),
                ],
                help_text="Denormalized from deliverable.type for fast lookup",
                max_length=20,
            ),
        ),
    ]
