# Generated by Django 5.2.15 on 2026-06-18 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StorePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("avatar_url", models.URLField(blank=True)),
                ("is_published", models.BooleanField(default=False)),
                ("theme", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Block",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("product", "Product"),
                            ("link", "Link"),
                            ("heading", "Heading"),
                            ("text", "Text"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveSmallIntegerField(default=0)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blocks",
                        to="catalog.product",
                    ),
                ),
                (
                    "store_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="blocks",
                        to="storefront.storepage",
                    ),
                ),
            ],
            options={
                "ordering": ["store_page", "position"],
            },
        ),
    ]
