# Generated by Django 5.2.15 on 2026-06-20 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_coursemodule_courselesson_courseprogress"),
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("page_view", "Page view"),
                            ("product_view", "Product view"),
                            ("checkout_start", "Checkout start"),
                            ("order_paid", "Order paid"),
                        ],
                        max_length=30,
                    ),
                ),
                ("session_key", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_events",
                        to="catalog.plan",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="page_events",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event", "created_at"], name="storefront__event_e36181_idx"
                    ),
                    models.Index(
                        fields=["product", "event"], name="storefront__product_99128d_idx"
                    ),
                ],
            },
        ),
    ]
