# Generated by Django 5.2.15 on 2026-06-20 03:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_sellerprofile_custom_domain_and_more"),
        ("storefront", "0002_pageevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="storepage",
            name="seller",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="store_page",
                to="accounts.sellerprofile",
            ),
        ),
    ]
