# Generated by Django 5.2.15 on 2026-08-29 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0003_storepage_seller"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="storepage",
            name="avatar_url",
        ),
        migrations.AddField(
            model_name="storepage",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="store/avatar/"),
        ),
        migrations.AddField(
            model_name="storepage",
            name="banner",
            field=models.ImageField(blank=True, null=True, upload_to="store/banner/"),
        ),
    ]
