# Generated by Django 5.2.15 on 2026-06-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotificationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("dedup_key", models.CharField(max_length=255, unique=True)),
                ("channel", models.CharField(max_length=20)),
                ("recipient", models.CharField(max_length=255)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
