# Generated by Django 5.2.15 on 2026-07-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailSuppression",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("hard_bounce", "Hard bounce"),
                            ("spam_complaint", "Spam complaint"),
                            ("manual", "Manually suppressed"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "detail",
                    models.TextField(
                        blank=True, help_text="Raw reason/diagnostic from the ESP, if any"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
