# Generated by Django 5.2.15 on 2026-08-29 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customer_notification_channel'),
        ('notifications', '0002_emailsuppression'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Normalized (62…) number.', max_length=20, unique=True)),
                ('reason', models.CharField(choices=[('opt_out', 'Replied STOP'), ('invalid_number', 'Invalid / unreachable number'), ('complaint', 'Complaint'), ('manual', 'Manually suppressed')], max_length=20)),
                ('detail', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(blank=True, max_length=80)),
                ('channel', models.CharField(max_length=20)),
                ('recipient', models.CharField(max_length=255)),
                ('wa_text', models.TextField(blank=True)),
                ('email_subject', models.CharField(blank=True, max_length=255)),
                ('email_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent to provider'), ('delivered', 'Delivered'), ('read', 'Read'), ('failed', 'Failed'), ('fallback_sent', 'Fell back to email')], default='queued', max_length=20)),
                ('provider', models.CharField(blank=True, max_length=20)),
                ('provider_msg_id', models.CharField(blank=True, max_length=128)),
                ('error', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='accounts.customer')),
            ],
            options={
                'verbose_name_plural': 'Notification deliveries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['provider_msg_id'], name='notificatio_provide_0edf59_idx')],
            },
        ),
    ]
